version: '3.7'

services:
  coturn:
    image: coturn/coturn:4.5.2
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "65435-65535:65435-65535/udp"
    command:
      - turnserver
      - --listening-port=3478
      - --realm=meetings.koktem2.kz
      - --user=turnuser:turnpass
      - --lt-cred-mech
      - --fingerprint
      - --no-multicast-peers
      - --no-cli
      - --no-tlsv1
      - --no-tlsv1_1
      - --external-ip=$$(detect-external-ip)
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=meetings
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    command: postgres -c 'max_connections=200'

  openvidu:
    image: openvidu/openvidu-server-kms:2.22.0
    environment:
      - OPENVIDU_SECRET=MY_SECRET
      - DOMAIN_OR_PUBLIC_IP=openvidu.koktem2.kz
      - HTTPS_PORT=443
      - OPENVIDU_CERTIFICATE_TYPE=selfsigned
      - OPENVIDU_RECORDING=false
      - OPENVIDU_STREAMS_VIDEO_MAX_RECV_BANDWIDTH=1000
      - OPENVIDU_STREAMS_VIDEO_MIN_RECV_BANDWIDTH=300
      - OPENVIDU_STREAMS_VIDEO_MAX_SEND_BANDWIDTH=1000
      - OPENVIDU_STREAMS_VIDEO_MIN_SEND_BANDWIDTH=300
      # COTURN TURN server configuration
      - COTURN_REDIS_IP=coturn
      - COTURN_REDIS_PASSWORD=turnpass
      - COTURN_IP=meetings.koktem2.kz
      - COTURN_PORT=3478
    depends_on:
      - coturn
    ports:
      - "4443:443"
    volumes:
      - ./recordings:/opt/openvidu/recordings
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  backend:
    build: ./server
    working_dir: /app
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - OPENVIDU_URL=https://openvidu.koktem2.kz
      - OPENVIDU_PUBLIC_URL=https://openvidu.koktem2.kz
      - OPENVIDU_SECRET=MY_SECRET
      - PORT=5005
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/meetings
    ports:
      - "5005:5005"
    depends_on:
      - openvidu
      - postgres
    restart: unless-stopped

  # frontend:
  #   build: ./client
  #   working_dir: /app
  #   volumes:
  #     - ./client:/app
  #   environment:
  #     - REACT_APP_SERVER_URL=http://localhost:5005
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   restart: unless-stopped

volumes:
  postgres_data: