version: '3.7'

services:
  coturn:
    image: coturn/coturn:4.5.2
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "65435-65535:65435-65535/udp"
    command:
      - turnserver
      - --listening-port=3478
      - --realm=meetings.koktem2.kz
      - --user=turnuser:turnpass
      - --lt-cred-mech
      - --fingerprint
      - --no-multicast-peers
      - --no-cli
      - --no-tlsv1
      - --no-tlsv1_1
      - --external-ip=$$(detect-external-ip)
    restart: unless-stopped
    networks:
      - meetings_network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=meetings
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    command: postgres -c 'max_connections=200'
    networks:
      - meetings_network

  openvidu:
    image: openvidu/openvidu-server-kms:2.22.0
    environment:
      - OPENVIDU_SECRET=MY_SECRET
      - DOMAIN_OR_PUBLIC_IP=openvidu.koktem2.kz
      - HTTPS_PORT=443
      - HTTP_PORT=80
      - OPENVIDU_CERTIFICATE_TYPE=selfsigned
      - OPENVIDU_RECORDING=false
      - OPENVIDU_STREAMS_VIDEO_MAX_RECV_BANDWIDTH=1000
      - OPENVIDU_STREAMS_VIDEO_MIN_RECV_BANDWIDTH=300
      - OPENVIDU_STREAMS_VIDEO_MAX_SEND_BANDWIDTH=1000
      - OPENVIDU_STREAMS_VIDEO_MIN_SEND_BANDWIDTH=300
      # WebRTC настройки
      - OPENVIDU_WEBRTC_ICE_SERVERS=[{"urls":["stun:stun.l.google.com:19302"]},{"urls":["turn:meetings.koktem2.kz:3478"],"username":"turnuser","credential":"turnpass"}]
      # Kurento настройки для лучшей совместимости
      - KMS_MIN_PORT=40000
      - KMS_MAX_PORT=57000
      # Отладка
      - OPENVIDU_LOG_LEVEL=DEBUG
    depends_on:
      - coturn
    ports:
      - "4443:443"
      - "4080:80"
      - "40000-57000:40000-57000/udp"
    volumes:
      - ./recordings:/opt/openvidu/recordings
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - meetings_network

  backend:
    build: ./server
    working_dir: /app
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - OPENVIDU_URL=https://openvidu.koktem2.kz
      - OPENVIDU_PUBLIC_URL=https://openvidu.koktem2.kz
      - OPENVIDU_SECRET=MY_SECRET
      - PORT=5005
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/meetings
    ports:
      - "5005:5005"
    depends_on:
      - openvidu
      - postgres
    restart: unless-stopped
    networks:
      - meetings_network

networks:
  meetings_network:
    driver: bridge

volumes:
  postgres_data: